#!/usr/bin/env bash

export BOX_NAME='fn'
export BASEBOX_NAME='akw'
export BASEBOX_HOME_URL='git@github.com:defn/home'

export BASEBOX_NETWORK_PREFIX='172.28.128'

export IP_alpha="${BASEBOX_NETWORK_PREFIX}.4"
export DOCKER_NETWORK_PREFIX_alpha='172.204.4'

export IP_beta="${BASEBOX_NETWORK_PREFIX}.5"
export DOCKER_NETWORK_PREFIX_kai='172.204.5'

export IP_omega="${BASEBOX_NETWORK_PREFIX}.6"
export DOCKER_NETWORK_PREFIX_omega='172.204.6'
