#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source inception_common

  limbo rebase
  limbo reuse vagrant
  limbo recycle
}

source sub "$BASH_SOURCE" "$@"
