#!/usr/bin/env bash

export VAGRANT_DEFAULT_PROVIDER='vmware'

__inception_net=3
case "${INCEPTION_DREAM}" in
  plane) __inception_net=1 ;;
  van)   __inception_net=2 ;;
  hotel) __inception_net=3 ;;
  show)  __inception_net=4 ;;
esac

export BASEBOX_IP="172.28.129.${__inception_net}"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.1${__inception_net}"

source sub-middleware "$BASH_SOURCE" "$@"
