#!/usr/bin/env bash

export BASEBOX_INSTANCE='hotel'
export BASEBOX_IP="172.28.128.5"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.5"
export VAGRANT_DEFAULT_PROVIDER='virtualbox'

source sub-middleware "$BASH_SOURCE" "$@"
