#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  eval $(reality docker machine env --swarm --no-proxy reality)
  exec docker "$@"
}

source sub "$BASH_SOURCE" "$@"
