#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  $INCEPTION clean

  $PLANE rebase
  $PLANE reuse vagrant
  $PLANE update
  $PLANE swarm primary
  $PLANE docker image rebase
  $PLANE docker image reuse

  $INCEPTION clean

  for a in virtualbox; do
    $PLANE "$a" recycle
    $PLANE "$a" update
    $PLANE "$a" docker image import
    $PLANE "$a" reuse
  done

  $INCEPTION clean

  for a in virtualbox; do
    $PLANE "$a" recycle
    $PLANE "$a" destroy -f
  done
}

source sub "$BASH_SOURCE" "$@"
