#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  $INCEPTION destroy -f
  $PLANE rebase
  $PLANE reuse vagrant

  $PLANE recycle
  $PLANE swarm primary
  $PLANE docker image rebase
  $PLANE docker image reuse

  $PLANE recycle
  $PLANE swarm primary
  $PLANE docker image import
  $PLANE reuse docker

  $INCEPTION destroy -f
}

source sub "$BASH_SOURCE" "$@"
