#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  sudo true
  runmany 10 'docker machine rm -f $1 2>&- ||  true; $1 destroy -f 2>&- || true' $PLANE $VAN $HOTEL $SNOW
}

source sub "$BASH_SOURCE" "$@"
