#!/usr/bin/env bash

export BOX_NAME='dream'
export BASEBOX_NAME='inception'
export BASEBOX_HOME_URL='git@github.com:defn/home'

export PLANE='planex'
export VAN='vanx'
export HOTEL='hotelx'
export SNOW='snowx'
export INCEPTION='inceptionx'
