#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  runmany '$1' docker image import "$@" -- $PLANE $VAN $HOTEL $SNOW
}

source sub "$BASH_SOURCE" "$@"
