#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  inception clean virtualbox
  inception clean vmware
  inception clean parallels
  inception clean vagrant
}

source sub "$BASH_SOURCE" "$@"
