#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source inception_common

  export LIMBO_LINKED_CLONES=0
  export BASEBOX_MACHINE=inception

  if [[ "$#" == 0 ]]; then
    set -- plane virtualbox
  fi

  while [[ "$#" != 0 ]]; do
    if [[ "$#" == 1 ]]; then
      set -- "$@" virtualbox
    fi

    b="$1"; shift
    a="$1"; shift

    export INCEPTION_DREAM="$b"
    source "reality_common"

    $b $a lxd init "${BASEBOX_NETWORK_PREFIX}"{0,9}
    $b vagrant ssh -- fanctl show | tail -n +2 | runmany 1 3 "$b"' vagrant ssh -- sudo fanctl down -u $2 -o $3'
    $b vagrant ssh -- sudo systemctl restart lxd-bridge

    $b $a docker init inception

    $b lxc exec inception -- lxc image copy ubuntu:16.04 local: --alias xenial

    $b docker pull "${CACHE_VIP}:5001/ubuntu:xenial"
    $b docker tag "${CACHE_VIP}:5001/ubuntu:xenial" "ubuntu:xenial"
    $b docker machine rm -f inception

    home remote init $b vagrant ssh --

    tar cf - /vagrant/{packages,curl} | $b lxc exec inception -- tar xvf - -C /
    $b lxc exec inception -- chown -R ubuntu:ubuntu /vagrant

    local ip_lxd="$($b lxc list inception --format json | jq -r '.[].state.network.eth0.addresses[] | select(.family == "inet").address')"
    ssh-keygen -R "$ip_lxd"
    home remote init ssh -A -o StrictHostKeyChecking=no ubuntu@"$ip_lxd"

    $b lxc stop inception

    $b vagrant ssh -- sudo rm -f /etc/default/lxd-bridge /etc/network/interfaces.d/99-limbo-fan.cfg

    $b vagrant ssh -- sudo lvcreate -s -n inception0 inception/inception
    $b lxc snapshot inception inception0

    $b $a reuse vagrant
  done
}

source sub "$BASH_SOURCE" "$@"
