#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source inception_common

  local nm_machine="$1"; shift
  eval $(docker machine env --no-proxy $nm_machine)
  
  local cnt_to="$1"; shift
  local cnt_many="$1"; shift

  seq 1 "$cnt_to" | while read a; do 
    printf '%s %s %q \n' "$a" "$nm_machine" "$*"
  done | runmany "$cnt_many" 3 'printf "%5d %10s %s\\n" "$1" "$2" "$(docker run --rm inception:vagrant $3)"'
}

source sub "$BASH_SOURCE" "$@"
