#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  $INCEPTION destroy -f
  runmany "$PLANE"' $1' rebase
  runmany "$PLANE"' docker image $1' rebase reuse
  runmany "$PLANE"' $1' reuse
}

source sub "$BASH_SOURCE" "$@"
