#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany '$1' docker image import "$@" -- plane van hotel snow
}

source sub "$BASH_SOURCE" "$@"
