#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  inception clean
  inception media
  inception clean
  inception build
  inception clean
  inception recycle
}

source sub "$BASH_SOURCE" "$@"
