#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany "$PLANE"' $1' provision reuse
  $INCEPTION destroy -f
  $INCEPTION build
}

source sub "$BASH_SOURCE" "$@"
