#!/usr/bin/env bash 

function main { 
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" 
  source inception_common 

  export LIMBO_LINKED_CLONES=1

  set -x

  while [[ "$#" != 0 ]]; do
    dream="$1"; shift

    case "$#" in
      1) a="virtualbox" ;;
      *) a="$1"; shift ;;
    esac

    dreamer="$1"; shift

    export INCEPTION_DREAM="$dream"
    source "reality_common"

    export LIMBO_FAST=1

    $dream $a init $dreamer
  done
}

source sub "$BASH_SOURCE" "$@"
