#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source inception_common

  runmany 'docker machine rm -f $1 2>&- ||  true' plane van hotel snow

  export LIMBO_LINKED_CLONES=1
  van virtualbox recycle
  hotel vmware recycle
  snow parallels recycle
}

source sub "$BASH_SOURCE" "$@"
