#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  inception media "$@"
  inception build "$@"
  inception recycle "$@"
}

source sub "$BASH_SOURCE" "$@"
