#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  inception clean virtualbox
  inception clean vagrant
}

source sub "$BASH_SOURCE" "$@"
