#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany 4 'docker machine rm -f $1 2>&- || true; $1 recycle; $1 swarm node' $PLANE $VAN $HOTEL $SNOW

  $PLANE swarm primary
  runmany 3 '$1 swarm node' $PLANE $VAN $HOTEL $SNOW

  docker machine ls
  $INCEPTION network create inception || true
}

source sub "$BASH_SOURCE" "$@"
