#!/usr/bin/env bash 

function dreamer {
  local b="$1"; shift
  case "$dream" in
    plane) echo fischer ;;
    van) echo yusuf ;;
    hotel) echo arthur ;;
    snow) echo eames ;;
  esac
}

function setup_consul {
  "$@" ln -nfs ../sv/consul service/
  "$@" bash -c "$(printf '%q' 'screen -S home-script-server -d -m script/server screen; sleep 5')"
  "$@" screen -X -S home-script-server quit
}

function main { 
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile" 
  source inception_common 

  export LIMBO_LINKED_CLONES=1

  set -x

  if [[ "$#" == 0 ]]; then
    set -- plane virtualbox
  fi

  while [[ "$#" != 0 ]]; do
    if [[ "$#" == 1 ]]; then
      set -- "$@" virtualbox
    fi

    dream="$1"; shift
    a="$1"; shift
    dreamer="$(dreamer $dream)"

    export INCEPTION_DREAM="$dream"
    source "reality_common"

    $dream $a recycle

    ssh-keygen -R $dream || true
    $dream $a init $dream
    ssh-keygen -R $dream || true
    setup_consul $dream vagrant ssh --

    ssh-keygen -R $dreamer || true
    $dream $a init $dreamer
    local ip_dreamer="$(env https_proxy= lxc list "$dream:$dreamer" --format json | jq -r '.[].state.network.br0.addresses[] | select(.family == "inet").address')"
    ssh-keygen -R "$ip_dreamer" || true
    setup_consul ssh -o StrictHostKeyChecking=no ubuntu@"$ip_dreamer" --

    $dreamer $a init lxd
  done
}

source sub "$BASH_SOURCE" "$@"
