#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  runmany 'reality $1' provision reuse
  inception destroy -f
  inception build
}

source sub "$BASH_SOURCE" "$@"
