#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  $INCEPTION destroy -f
  rm -rf ~/.vagrant.d/tmp
  rm -rf ${CACHE_DIR}/output
}

source sub "$BASH_SOURCE" "$@"
