#!/usr/bin/env bash

export BOX_NAME='dream'
export BASEBOX_NAME='inception'
export BASEBOX_HOME_URL='git@github.com:defn/home'

export DREAM_NETWORK_PREFIX='172.29'
export BASEBOX_NETWORK_PREFIX='172.28.128'

export DREAM_IP_reality="${BASEBOX_NETWORK_PREFIX}.1"
export DREAM_NETWORK_PREFIX_reality="${DREAM_NETWORK_PREFIX}.1"
case "$(uname -s)" in
  Darwin)
    export DREAM_NETWORK_PREFIX_reality="${DREAM_NETWORK_PREFIX}.3"
    export BASEBOX_DOCKER_OCTET="3"
    ;;
esac

export DREAM_IP_dream="${BASEBOX_NETWORK_PREFIX}.3"
export DREAM_NETWORK_PREFIX_dream="${DREAM_NETWORK_PREFIX}.3"

export DREAM_IP_van="${BASEBOX_NETWORK_PREFIX}.4"
export DREAM_NETWORK_PREFIX_van="${DREAM_NETWORK_PREFIX}.4"

export DREAM_IP_hotel="${BASEBOX_NETWORK_PREFIX}.5"
export DREAM_NETWORK_PREFIX_hotel="${DREAM_NETWORK_PREFIX}.5"

export DREAM_IP_fortress="${BASEBOX_NETWORK_PREFIX}.6"
export DREAM_NETWORK_PREFIX_fortress="${DREAM_NETWORK_PREFIX}.6"
