#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if type -P VBoxManager >/dev/null; then
    VBoxManage list vms 2>/dev/null | cut -d'"' -f2 | runmany 'VBoxManage controlvm $1 poweroff || true; VBoxManage unregistervm --delete $1 || true'
  fi
}

source sub "$BASH_SOURCE" "$@"
