#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  sudo true
  runmany 10 'docker machine rm -f $1; $1 destroy -f' plane van hotel snow
}

source sub "$BASH_SOURCE" "$@"
