#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source inception_common

  if [[ "$#" == 0 ]]; then
    set -- virtualbox vmware parallels
  fi

  for a in "$@"; do
    case "$a" in
      plane)
        a=virtualbox
        b=plane
        ;;
      virtualbox|van)
        a=virtualbox
        b=van
        ;;
      vmware|hotel)
        a=vmware
        b=hotel
        ;;
      parallels|snow) 
        a=parallels
        b=snow
        ;;
    esac
    export INCEPTION_DREAM="$b"
    source "reality_common"
    $b $a recycle
    $b $a lxd init "${BASEBOX_NETWORK_PREFIX}"0
    $b $a docker init inception "${BASEBOX_NETWORK_PREFIX}1" $b "${BASEBOX_NETWORK_PREFIX}9"
    $b docker pull $CACHE_VIP:5000/inception:vagrant
    $b docker tag $CACHE_VIP:5000/inception:vagrant inception:vagrant
    $b lxc stop inception
    $b vagrant ssh -- sudo lvcreate -s -n inception0 system/inception
    $b lxc snapshot inception inception0
    $b $a reuse
  done
}

source sub "$BASH_SOURCE" "$@"
