#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  prlctl list -a | tail +2 | awk '{print $NF}' | runmany 'prlctl stop $1 || true; prlctl delete $1 || true'
  (set +f; rm -rf ~/Documents/Parallels)
}

source sub "$BASH_SOURCE" "$@"
