#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  inception media "$@"
  (cd && home remote init "$1" vagrant ssh --)
  inception build "$@"
  inception recycle "$@"
}

source sub "$BASH_SOURCE" "$@"
