#!/usr/bin/env bash

source normalize

export BOX_NAME='dream'
export BASEBOX_NAME='inception'
export BASEBOX_HOME_URL='git@github.com:defn/home'

function limbo {
  if [[ -n "${VAGRANT_DEFAULT_PROVIDER:-}" ]]; then
    set -- "${VAGRANT_DEFAULT_PROVIDER}" "$@"
  fi

  command limbo "$@"
}
