#!/usr/bin/env bash

unset https_proxy

lxc remote set-default "${BASEBOX_INSTANCE:-}" 2>/dev/null || true

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  exec lxc "$@"
}

source sub "$BASH_SOURCE" "$@"
