#!/usr/bin/env bash

unset http_proxy https_proxy

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  exec lxc "$@"
}

source sub "$BASH_SOURCE" "$@"
