#!/usr/bin/env bash

function main {
  local shome="${_inception_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"
  source "$shome/exec/inception"

  exec limbo "${INCEPTION_PROVIDER}" "$@"
}

source sub "$BASH_SOURCE" "$@"
