#!/usr/bin/env bash

export BASEBOX_INSTANCE='plane'
export BASEBOX_IP="172.28.129.3"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.13"
export INCEPTION_PROVIDER='vmware'

source sub-middleware "$BASH_SOURCE" "$@"
