#!/usr/bin/env bash

eval $(docker machine env --no-proxy $INCEPTION_DREAM 2>&-)

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source inception_common

  exec limbo docker "$@"
}

source sub "$BASH_SOURCE" "$@"
