#!/usr/bin/env bash

export VAGRANT_DEFAULT_PROVIDER='virtualbox'

case "${INCEPTION_DREAM}" in
  plane) __inception_net=2 ;;
  van)   __inception_net=3 ;;
  hotel) __inception_net=4 ;;
  snow)  __inception_net=5 ;;
esac

export BASEBOX_IP="172.28.128.${__inception_net}"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.1${__inception_net}"
export BASEBOX_LXD_NETWORK_PREFIX="172.29.2${__inception_net}"

source sub-middleware "$BASH_SOURCE" "$@"
