#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source inception_common

  exec limbo docker "$@"
}

source sub "$BASH_SOURCE" "$@"
