#!/usr/bin/env bash

export VAGRANT_DEFAULT_PROVIDER='aws'

case "${INCEPTION_DREAM}" in
  plane) __inception_net=2 ;;
  van)   __inception_net=3 ;;
  hotel) __inception_net=4 ;;
  snow)  __inception_net=5 ;;
esac

export BASEBOX_IP="172.28.28.${__inception_net}"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.7${__inception_net}"
export BASEBOX_LXD_NETWORK_PREFIX="172.29.8${__inception_net}"

export EC2_TARGET_AMI_NAME="${CONTEXT_ORG}-${CONTEXT_ENV}-$(date +%s)"
export EC2_INSTANCE_TYPE="t2.medium"

source sub-middleware "$BASH_SOURCE" "$@"
