#!/usr/bin/env bash

export BASEBOX_INSTANCE='van'
export BASEBOX_IP="172.28.128.4"
export BASEBOX_DOCKER_NETWORK_PREFIX="172.29.4"
export INCEPTION_PROVIDER='virtualbox'

source sub-middleware "$BASH_SOURCE" "$@"
