#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  exec reality "$(basename "${BASH_SOURCE}")" "$@"
}

source sub "$BASH_SOURCE" "$@"
