#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  source "$shome/exec/inception"

  export BASEBOX_INSTANCE="$(basename "$BASH_SOURCE")"

  local nm_ip="DREAM_IP_${BASEBOX_INSTANCE}"
  local nm_docker="DREAM_NETWORK_PREFIX_${BASEBOX_INSTANCE}"

  export BASEBOX_IP="${!nm_ip}"
  export BASEBOX_DOCKER_NETWORK_PREFIX="${!nm_docker}"

  case "$BASEBOX_INSTANCE" in
    reality)
      case "${1:-}" in
        build)
          cd
          exec block cibuild
          ;;
        *)
          exec limbo "$@"
          ;;
        esac
      ;;
    *)
      exec limbo "$@"
      ;;
  esac
}

source sub "$BASH_SOURCE" "$@"
