#!/usr/bin/env bash

function _inception_profile {
  local shome="${_inception_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
}

_inception_profile
